/**
 * Dashboard Widget Registry — single source of truth for every widget the
 * dashboard can render. The registry drives:
 *
 *   1. Which cards appear in the admin workbench palette
 *   2. Which cards the dashboard screen can render
 *   3. The seed data for tbldashboard_widgets on the backend
 *   4. Permission gating (only show if user has feature access)
 *
 * To add a new module widget: add an entry here, create its query hook,
 * and it shows up everywhere automatically.
 */

export type WidgetSize = "1x1" | "2x1" | "1x2" | "2x2";
export type WidgetComponentType = "stat" | "chart" | "list" | "action";

export type WidgetDef = {
  key: string;
  title: string;
  icon: string;
  color: string;
  componentType: WidgetComponentType;
  defaultSize: WidgetSize;
  sizes: WidgetSize[];
  /** Perfex permission feature key — null means always visible */
  permissionFeature: string | null;
  /** Source module for grouping in the palette */
  module: string;
  /** Route to navigate when tapped */
  route: string;
  /** Sort order in the palette (lower = first) */
  sortOrder: number;
};

export const WIDGET_REGISTRY: Record<string, WidgetDef> = {
  tasks_summary: {
    key: "tasks_summary",
    title: "My Tasks",
    icon: "checkbox-outline",
    color: "#F59E0B",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "tasks",
    module: "tasks",
    route: "/(tabs)/tasks?filter=mine",
    sortOrder: 10,
  },
  projects: {
    key: "projects",
    title: "Active Projects",
    icon: "folder-outline",
    color: "#0284C7",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "projects",
    module: "projects",
    route: "/(tabs)/projects",
    sortOrder: 20,
  },
  customers: {
    key: "customers",
    title: "Customers",
    icon: "business-outline",
    color: "#8B5CF6",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "customers",
    module: "customers",
    route: "/(tabs)/customers",
    sortOrder: 30,
  },
  leads: {
    key: "leads",
    title: "Total Leads",
    icon: "people-outline",
    color: "#16A34A",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "leads",
    module: "leads",
    route: "/(tabs)/erp/leads",
    sortOrder: 40,
  },
  invoices: {
    key: "invoices",
    title: "Invoices",
    icon: "document-text-outline",
    color: "#EF4444",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "invoices",
    module: "invoices",
    route: "/(tabs)/erp/invoices",
    sortOrder: 50,
  },
  approvals_pending: {
    key: "approvals_pending",
    title: "Pending Approvals",
    icon: "shield-checkmark-outline",
    color: "#7C3AED",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: null,
    module: "approvals",
    route: "/(tabs)/approvals",
    sortOrder: 60,
  },
  estimates: {
    key: "estimates",
    title: "Estimates",
    icon: "calculator-outline",
    color: "#0369A1",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "estimates",
    module: "estimates",
    route: "/(tabs)/erp/estimates",
    sortOrder: 70,
  },
  proposals: {
    key: "proposals",
    title: "Proposals",
    icon: "reader-outline",
    color: "#CA8A04",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "proposals",
    module: "proposals",
    route: "/(tabs)/erp/proposals",
    sortOrder: 80,
  },
  tickets: {
    key: "tickets",
    title: "Open Tickets",
    icon: "chatbox-ellipses-outline",
    color: "#DC2626",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "tickets",
    module: "tickets",
    route: "/(tabs)/tickets",
    sortOrder: 90,
  },
  contracts: {
    key: "contracts",
    title: "Active Contracts",
    icon: "document-lock-outline",
    color: "#059669",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "contracts",
    module: "contracts",
    route: "/(tabs)/erp/contracts",
    sortOrder: 100,
  },
  expenses: {
    key: "expenses",
    title: "My Expenses",
    icon: "receipt-outline",
    color: "#EA580C",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "expenses",
    module: "expenses",
    route: "/(tabs)/expenses-mine",
    sortOrder: 110,
  },
  tenders: {
    key: "tenders",
    title: "Active Tenders",
    icon: "briefcase-outline",
    color: "#2563EB",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "przpurchase",
    module: "tenders",
    route: "/(tabs)/erp/tenders",
    sortOrder: 120,
  },
  opportunities: {
    key: "opportunities",
    title: "Opportunities",
    icon: "trending-up-outline",
    color: "#4F46E5",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: null,
    module: "opportunities",
    route: "/(tabs)/erp/opportunities",
    sortOrder: 130,
  },

  // ── Batch 1: Tasks (granular) ──────────────────────────────────────────
  tasks_open: {
    key: "tasks_open",
    title: "My Open Tasks",
    icon: "checkbox-outline",
    color: "#F59E0B",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "tasks",
    module: "tasks",
    route: "/(tabs)/tasks?filter=mine",
    sortOrder: 250,
  },
  tasks_overdue: {
    key: "tasks_overdue",
    title: "Overdue Tasks",
    icon: "alert-circle-outline",
    color: "#DC2626",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: "tasks",
    module: "tasks",
    route: "/(tabs)/tasks?filter=overdue",
    sortOrder: 260,
  },
  tasks_status_chart: {
    key: "tasks_status_chart",
    title: "Tasks by Status",
    icon: "pie-chart-outline",
    color: "#F59E0B",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "tasks",
    module: "tasks",
    route: "/(tabs)/tasks",
    sortOrder: 270,
  },
  tasks_due_today: {
    key: "tasks_due_today",
    title: "Tasks Due Today",
    icon: "today-outline",
    color: "#B45309",
    componentType: "list",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "tasks",
    module: "tasks",
    route: "/(tabs)/tasks?filter=today",
    sortOrder: 280,
  },
  tasks_stale: {
    key: "tasks_stale",
    title: "Stale Tasks",
    icon: "hourglass-outline",
    color: "#64748B",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "tasks",
    module: "tasks",
    route: "/(tabs)/tasks?filter=stale",
    sortOrder: 290,
  },
  tasks_completed_30d: {
    key: "tasks_completed_30d",
    title: "Completed (30d)",
    icon: "checkmark-done-outline",
    color: "#15803D",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "tasks",
    module: "tasks",
    route: "/(tabs)/tasks?filter=completed",
    sortOrder: 300,
  },

  // ── Batch 1: Approvals (granular) ──────────────────────────────────────
  approvals_my_pending: {
    key: "approvals_my_pending",
    title: "My Pending Approvals",
    icon: "shield-checkmark-outline",
    color: "#7C3AED",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: null,
    module: "approvals",
    route: "/(tabs)/approvals",
    sortOrder: 310,
  },
  approvals_recent: {
    key: "approvals_recent",
    title: "Recent Approvals",
    icon: "list-outline",
    color: "#7C3AED",
    componentType: "list",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: null,
    module: "approvals",
    route: "/(tabs)/approvals",
    sortOrder: 320,
  },
  approvals_by_type: {
    key: "approvals_by_type",
    title: "Approvals by Type",
    icon: "pie-chart-outline",
    color: "#7C3AED",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: null,
    module: "approvals",
    route: "/(tabs)/approvals",
    sortOrder: 330,
  },

  // ── Batch 1: Timesheets/Attendance ─────────────────────────────────────
  attendance_status: {
    key: "attendance_status",
    title: "Clock In/Out Status",
    icon: "log-in-outline",
    color: "#0369A1",
    componentType: "action",
    defaultSize: "1x1",
    sizes: ["1x1", "2x1"],
    permissionFeature: null,
    module: "timesheets",
    route: "/(tabs)/timesheets",
    sortOrder: 340,
  },
  timesheet_hours_week: {
    key: "timesheet_hours_week",
    title: "Hours This Week",
    icon: "time-outline",
    color: "#0369A1",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: null,
    module: "timesheets",
    route: "/(tabs)/timesheets",
    sortOrder: 350,
  },
  timesheet_pending: {
    key: "timesheet_pending",
    title: "Pending Timesheets",
    icon: "document-outline",
    color: "#0369A1",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: null,
    module: "timesheets",
    route: "/(tabs)/timesheets",
    sortOrder: 360,
  },

  // ── Batch 2: Leave ─────────────────────────────────────────────────────
  leave_balance: {
    key: "leave_balance",
    title: "Leave Balance",
    icon: "leaf-outline",
    color: "#15803D",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: null,
    module: "hr",
    route: "/(tabs)/leave",
    sortOrder: 370,
  },
  leave_pending: {
    key: "leave_pending",
    title: "My Pending Leaves",
    icon: "hourglass-outline",
    color: "#B45309",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: null,
    module: "hr",
    route: "/(tabs)/leave",
    sortOrder: 380,
  },
  leave_upcoming: {
    key: "leave_upcoming",
    title: "Upcoming Leaves",
    icon: "calendar-outline",
    color: "#0284C7",
    componentType: "list",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: null,
    module: "hr",
    route: "/(tabs)/leave",
    sortOrder: 390,
  },

  // ── Batch 2: Payslip ───────────────────────────────────────────────────
  payslip_latest: {
    key: "payslip_latest",
    title: "Latest Payslip",
    icon: "wallet-outline",
    color: "#4F46E5",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: null,
    module: "hr_payroll",
    route: "/(tabs)/payslips",
    sortOrder: 400,
  },

  // ── Batch 2: Expenses (granular) ──────────────────────────────────────
  expenses_total_month: {
    key: "expenses_total_month",
    title: "My Expenses (Month)",
    icon: "receipt-outline",
    color: "#EA580C",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "expenses",
    module: "expenses",
    route: "/(tabs)/expenses-mine",
    sortOrder: 410,
  },
  expenses_pending: {
    key: "expenses_pending",
    title: "Pending Expenses",
    icon: "time-outline",
    color: "#EA580C",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "expenses",
    module: "expenses",
    route: "/(tabs)/expenses-mine",
    sortOrder: 420,
  },
  expenses_by_category: {
    key: "expenses_by_category",
    title: "Expenses by Category",
    icon: "pie-chart-outline",
    color: "#EA580C",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "expenses",
    module: "expenses",
    route: "/(tabs)/expenses-mine",
    sortOrder: 430,
  },

  // ── Batch 3: Projects ──────────────────────────────────────────────────
  projects_by_status: {
    key: "projects_by_status",
    title: "Projects by Status",
    icon: "pie-chart-outline",
    color: "#0284C7",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "projects",
    module: "projects",
    route: "/(tabs)/projects",
    sortOrder: 440,
  },
  projects_overdue: {
    key: "projects_overdue",
    title: "Overdue Projects",
    icon: "alert-circle-outline",
    color: "#DC2626",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "projects",
    module: "projects",
    route: "/(tabs)/projects",
    sortOrder: 450,
  },
  projects_revenue: {
    key: "projects_revenue",
    title: "Project Revenue",
    icon: "cash-outline",
    color: "#16A34A",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "projects",
    module: "projects",
    route: "/(tabs)/projects",
    sortOrder: 460,
  },
  projects_recent_activity: {
    key: "projects_recent_activity",
    title: "Recent Project Activity",
    icon: "pulse-outline",
    color: "#0284C7",
    componentType: "list",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "projects",
    module: "projects",
    route: "/(tabs)/projects",
    sortOrder: 470,
  },
  projects_my_active: {
    key: "projects_my_active",
    title: "My Active Projects",
    icon: "folder-outline",
    color: "#0284C7",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "projects",
    module: "projects",
    route: "/(tabs)/projects",
    sortOrder: 480,
  },

  // ── Batch 3: Invoices ──────────────────────────────────────────────────
  invoices_overdue: {
    key: "invoices_overdue",
    title: "Overdue Invoices",
    icon: "alert-circle-outline",
    color: "#EF4444",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "invoices",
    module: "invoices",
    route: "/(tabs)/erp/invoices",
    sortOrder: 490,
  },
  invoices_total_month: {
    key: "invoices_total_month",
    title: "Invoiced This Month",
    icon: "document-text-outline",
    color: "#EF4444",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "invoices",
    module: "invoices",
    route: "/(tabs)/erp/invoices",
    sortOrder: 500,
  },
  invoices_by_status: {
    key: "invoices_by_status",
    title: "Invoices by Status",
    icon: "pie-chart-outline",
    color: "#EF4444",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "invoices",
    module: "invoices",
    route: "/(tabs)/erp/invoices",
    sortOrder: 510,
  },
  invoices_aging: {
    key: "invoices_aging",
    title: "Invoice Aging",
    icon: "bar-chart-outline",
    color: "#EF4444",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "invoices",
    module: "invoices",
    route: "/(tabs)/erp/invoices",
    sortOrder: 520,
  },

  // ── Batch 3: Leads ─────────────────────────────────────────────────────
  leads_by_status: {
    key: "leads_by_status",
    title: "Leads by Status",
    icon: "pie-chart-outline",
    color: "#16A34A",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "leads",
    module: "leads",
    route: "/(tabs)/erp/leads",
    sortOrder: 530,
  },
  leads_by_source: {
    key: "leads_by_source",
    title: "Leads by Source",
    icon: "pie-chart-outline",
    color: "#16A34A",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "leads",
    module: "leads",
    route: "/(tabs)/erp/leads",
    sortOrder: 540,
  },
  leads_converted_month: {
    key: "leads_converted_month",
    title: "Converted (Month)",
    icon: "checkmark-done-outline",
    color: "#15803D",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "leads",
    module: "leads",
    route: "/(tabs)/erp/leads",
    sortOrder: 550,
  },
  leads_value_pipeline: {
    key: "leads_value_pipeline",
    title: "Pipeline Value",
    icon: "trending-up-outline",
    color: "#16A34A",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "leads",
    module: "leads",
    route: "/(tabs)/erp/leads",
    sortOrder: 560,
  },

  // ── Batch 3: Tickets ───────────────────────────────────────────────────
  tickets_open_count: {
    key: "tickets_open_count",
    title: "Open Tickets",
    icon: "chatbox-ellipses-outline",
    color: "#DC2626",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "tickets",
    module: "tickets",
    route: "/(tabs)/tickets",
    sortOrder: 570,
  },
  tickets_by_priority: {
    key: "tickets_by_priority",
    title: "Tickets by Priority",
    icon: "pie-chart-outline",
    color: "#DC2626",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "tickets",
    module: "tickets",
    route: "/(tabs)/tickets",
    sortOrder: 580,
  },
  tickets_avg_response: {
    key: "tickets_avg_response",
    title: "Avg Response Time",
    icon: "speedometer-outline",
    color: "#DC2626",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "tickets",
    module: "tickets",
    route: "/(tabs)/tickets",
    sortOrder: 590,
  },
  tickets_my_assigned: {
    key: "tickets_my_assigned",
    title: "My Assigned Tickets",
    icon: "person-outline",
    color: "#DC2626",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "tickets",
    module: "tickets",
    route: "/(tabs)/tickets",
    sortOrder: 600,
  },

  // ── Batch 3: Contracts ─────────────────────────────────────────────────
  contracts_expiring_soon: {
    key: "contracts_expiring_soon",
    title: "Expiring Soon",
    icon: "warning-outline",
    color: "#059669",
    componentType: "list",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "contracts",
    module: "contracts",
    route: "/(tabs)/erp/contracts",
    sortOrder: 610,
  },
  contracts_by_type: {
    key: "contracts_by_type",
    title: "Contracts by Type",
    icon: "pie-chart-outline",
    color: "#059669",
    componentType: "chart",
    defaultSize: "2x1",
    sizes: ["2x1", "2x2"],
    permissionFeature: "contracts",
    module: "contracts",
    route: "/(tabs)/erp/contracts",
    sortOrder: 620,
  },
  contracts_value: {
    key: "contracts_value",
    title: "Total Contract Value",
    icon: "cash-outline",
    color: "#059669",
    componentType: "stat",
    defaultSize: "1x1",
    sizes: ["1x1"],
    permissionFeature: "contracts",
    module: "contracts",
    route: "/(tabs)/erp/contracts",
    sortOrder: 630,
  },
};

/** All registered widget keys, sorted by sortOrder */
export const ALL_WIDGET_KEYS = Object.values(WIDGET_REGISTRY)
  .sort((a, b) => a.sortOrder - b.sortOrder)
  .map((w) => w.key);

/** Get a widget definition by key. Returns undefined for unknown keys. */
export function getWidget(key: string): WidgetDef | undefined {
  return WIDGET_REGISTRY[key];
}

/** List all widgets that the given permission checker allows. */
export function getVisibleWidgets(
  hasAnyPermission: (feature: string) => boolean
): WidgetDef[] {
  return Object.values(WIDGET_REGISTRY)
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .filter((w) => !w.permissionFeature || hasAnyPermission(w.permissionFeature));
}
